name: "Run JavaScript Action"
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Strech/run-javascript-action@master
        name: Get Berlin weather
        id: weather
        with:
          script: |
            // NOTE: You can output to the standard console
            console.log("You can output to the standard console")

            // NOTE: You also will have access to some libraries
            //       stored in the `$` object
            const response = await $.fetch("https://wttr.in/Berlin", {
              headers: { "User-Agent": "curl" }
             }).then(res => res.text());

            return response
      - name: Print weather
        run: |
          echo "${{ steps.weather.outputs.result }}"
